name = "Move To Control Register"

mnemonic = "MTCR Cs, Ra"

encoding = "111000000000ssssaaaaa00000101001"

text = """

Sets the value of a control register to the value stored in a general purpose register.

"""

implementation = """

ra = (ir >> 11) & 31;
rb = (ir >> 16) & 15;

ControlReg[rb] = Reg[ra];

"""

notes = """"""

