name = "???"

mnemonic = "TBLD ???, ???"

encoding = "0011000000000000aaaaaddddd101001"

text = """

???

"""

implementation = """

rd = (ir >> 6) & 31;
ra = (ir >> 11) & 31;

pde = Reg[ra];
  
if (!(pde & 1)) {
    Reg[rd] = 0;
    break;
}
  
CPUReadLong(((pde >> 5) << 12) | ((ControlReg[TBHI] & 1023) << 2), &Reg[rd]);

"""

notes = """"""

