name = "???"

mnemonic = "TBRD"

encoding = "00100000000000000000000000101001"

text = """

???

"""

implementation = """

tlbe = TLB[ControlReg[TBINDEX] & (TLBSIZE - 1)];
  
ControlReg[TBLO] = tlbe;
ControlReg[TBHI] = tlbe >> 32;

"""

notes = """"""

